const toursData = [
  {
    id: "askold",
    tag: "Остров",
    name: "Остров Аскольд",
    desc: "Морской переход, тюлени ларги на лежбищах, руины старинных построек и величественный маяк Аскольд.",
    price: "7 500",
    img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=500&q=80",
    schedule: "По запросу",
    departure: "09:00",
    duration: "10 ч",
    bookedDates: [
      "2026-06-07",
      "2026-06-14",
      "2026-06-21",
      "2026-06-28",
      "2026-07-05",
      "2026-07-12",
      "2026-07-19",
      "2026-07-26",
    ],
  },
  {
    id: "safari",
    tag: "Дикая природа",
    name: "Сафари Парк (три парка)",
    desc: "Тигры, леопарды, медведи и олени в естественной среде обитания. Без клеток и ограждений.",
    price: "5 100",
    img: "img/tours/safari_1.webp",
    schedule: "Понедельник",
    departure: "09:00",
    duration: "7 ч",
    bookedDates: [
      "2026-06-08",
      "2026-06-15",
      "2026-06-22",
      "2026-06-29",
      "2026-07-06",
      "2026-07-13",
      "2026-07-20",
      "2026-07-27",
    ],
  },
  {
    id: "ocean",
    tag: "Экскурсия",
    name: "Приморский Океанариум",
    desc: "Один из крупнейших океанариумов мира на острове Русский. Обитатели всех океанов и климатических зон Земли.",
    price: "3 500",
    img: "img/tours/oreonarium_2.webp",
    schedule: "Вторник",
    departure: "08:00",
    duration: "12 ч",
    bookedDates: [
      "2026-06-09",
      "2026-06-16",
      "2026-06-23",
      "2026-06-30",
      "2026-07-07",
      "2026-07-14",
      "2026-07-21",
      "2026-07-28",
    ],
  },
  {
    id: "livadia",
    tag: "Побережье",
    name: "Ливадийское побережье и бухта Рифовая",
    desc: "Экскурсия по Ливадийским бухтам, посещение музея и отдых на пляже бухты Рифовой.",
    price: "3 500",
    img: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=500&q=80",
    schedule: "Среда",
    departure: "По запросу",
    duration: "Весь день",
    bookedDates: [
      "2026-06-10",
      "2026-06-17",
      "2026-06-24",
      "2026-07-01",
      "2026-07-08",
      "2026-07-15",
    ],
  },
  {
    id: "sestra",
    tag: "Треккинг",
    name: "Сопка Сестра + Бухта Лашкевича",
    desc: "Живописный подъём 40–60 минут. С вершины — панорама залива Находка, порта и бескрайнего Японского моря. Купание после.",
    price: "3 000",
    img: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=500&q=80",
    schedule: "Четверг",
    departure: "15:00",
    duration: "5 ч",
    bookedDates: [
      "2026-06-11",
      "2026-06-18",
      "2026-06-25",
      "2026-07-02",
      "2026-07-09",
      "2026-07-16",
    ],
  },
  {
    id: "putyatin",
    tag: "Остров",
    name: "Красоты острова Путятин",
    desc: "Скалистые бухты и дикие побережья острова с борта катера. Купание в чистейших водах Японского моря.",
    price: "6 200",
    img: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?auto=format&fit=crop&w=500&q=80",
    schedule: "Пятница",
    departure: "09:00",
    duration: "11 ч",
    bookedDates: [
      "2026-06-12",
      "2026-06-19",
      "2026-06-26",
      "2026-07-03",
      "2026-07-10",
      "2026-07-17",
    ],
  },
  {
    id: "lotus",
    tag: "Август",
    name: "Путятин + цветение лотосов",
    desc: "Морское путешествие вокруг острова Путятин. Озеро, покрытое розовыми лотосами — незабываемое зрелище!",
    price: "8 000",
    img: "https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=500&q=80",
    schedule: "Август",
    departure: "09:00",
    duration: "11 ч",
    bookedDates: [],
  },
  {
    id: "vladivostok1",
    tag: "Владивосток",
    name: "Владивосток: Нагорный парк, маяк Токаревский",
    desc: "Нагорный парк с видом на город и залив, смотровая Бурачка, исторический Токаревский маяк — символ Владивостока.",
    price: "4 000",
    img: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=500&q=80",
    schedule: "Понедельник",
    departure: "07:00",
    duration: "13 ч",
    bookedDates: ["2026-06-08", "2026-06-15", "2026-06-22", "2026-06-29"],
  },
  {
    id: "botsad",
    tag: "Владивосток",
    name: "Ботсад + зоопарк Садгород + б.Стеклянная",
    desc: "Три в одном: тенистые аллеи ботсада, уютный зоопарк с любовью к животным и уникальный пляж бухты Стеклянной.",
    price: "5 500",
    img: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=500&q=80",
    schedule: "Среда",
    departure: "08:00",
    duration: "12 ч",
    bookedDates: ["2026-06-10", "2026-06-17", "2026-06-24"],
  },
  {
    id: "vladivostok2",
    tag: "Владивосток",
    name: "Музей ДВ + пешеходная экскурсия",
    desc: "Музей Арсеньева и пешеходная экскурсия по центру: Светланская, набережная Амурского залива, Корабельная набережная.",
    price: "6 500",
    img: "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=500&q=80",
    schedule: "Четверг",
    departure: "07:00",
    duration: "13 ч",
    bookedDates: ["2026-06-11", "2026-06-18", "2026-06-25"],
  },
  {
    id: "waterfall",
    tag: "Выходные",
    name: "Водопад Стеклянуха",
    desc: "Водопад высотой 12 метров, окружённый вулканическими восьмиугольными столбами. Громкий, красивый, завораживающий.",
    price: "5 000",
    img: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=500&q=80",
    schedule: "Воскресенье",
    departure: "09:00",
    duration: "9 ч",
    bookedDates: [],
  },
  {
    id: "individual",
    tag: "Индивидуально",
    name: "Индивидуальная экскурсия по Находке",
    desc: "Городская часть + природная локация на выбор: мыс Пассека, маяк Лихачёва, тропа Осьминога, японский сад Эниси, Ливадия.",
    price: "12 000",
    img: "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=500&q=80",
    schedule: "По запросу",
    departure: "По договорённости",
    duration: "Весь день",
    bookedDates: [],
  },
  {
    id: "boats-yachts",
    tag: "Море",
    name: "Морские прогулки на катерах и яхтах",
    desc: "Прогулки на катерах и яхтах вдоль побережья Находки — для тех, кто хочет встретить день или закат на воде.",
    price: "3 000",
    img: "img/tours/boat_yacht.webp",
    schedule: "Ежедневно",
    departure: "По расписанию",
    duration: "2–4 ч",
    bookedDates: [],
  },
  {
    id: "triozerye-classic",
    tag: "Бухта",
    name: "Бухта Триозерье",
    desc: "Только вы, море и песок. Классический пляжный выезд в одну из самых живописных бухт Находки.",
    price: "2 500",
    img: "img/tours/3_ozera_3.webp",
    schedule: "Ежедневно",
    departure: "11:00",
    duration: "6 ч",
    bookedDates: [],
  },
  {
    id: "okunevaya-jeep",
    tag: "Джип-тур",
    name: "Бухта Окуневая (джип-тур)",
    desc: "Внедорожный выезд к бухте Окуневой — для тех, кто хочет добраться с комфортом и приключением по пути.",
    price: "3 000",
    img: "img/tours/okunev_1.webp",
    schedule: "Ежедневно",
    departure: "11:00",
    duration: "6 ч",
    bookedDates: [],
  },
  {
    id: "spokoinaya-jeep",
    tag: "Джип-тур",
    name: "Бухта Спокойная (джип-тур)",
    desc: "Тихая, малолюдная бухта в стороне от туристических троп. Добираемся на внедорожнике с остановками по пути.",
    price: "3 500",
    img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=500&q=80",
    schedule: "Ежедневно",
    departure: "11:00",
    duration: "6 ч",
    bookedDates: [],
  },
  {
    id: "nahodka-excursion",
    tag: "Выходные",
    name: "Экскурсия по Находке",
    desc: "Обзорная экскурсия по вечернему городу. Богатое прошлое Находки и местные достопримечательности.",
    price: "2 000",
    img: "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=500&q=80",
    schedule: "Суббота",
    departure: "По расписанию",
    duration: "3 ч",
    bookedDates: [],
  },
  {
    id: "enisi-garden",
    tag: "Выходные",
    name: "Японский сад «Эниси»",
    desc: "Маленький уголок Японии: прогулка по японскому саду и традиционная чайная церемония.",
    price: "1 500",
    img: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=500&q=80",
    schedule: "Суббота",
    departure: "По расписанию",
    duration: "2 ч",
    bookedDates: [],
  },
  {
    id: "nahodka-charm",
    tag: "Выходные",
    name: "Очарование Находки",
    desc: "С посещением природных достопримечательностей города. Атмосфера Находки и природа в одном маршруте.",
    price: "2 500",
    img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=500&q=80",
    schedule: "Воскресенье",
    departure: "По расписанию",
    duration: "4 ч",
    bookedDates: [],
  },
];

const achievementsList = [
  {
    id: 1,
    icon: "🌱",
    titleRu: "Первый шаг",
    descRu: "Совершил первое путешествие с Лотос-тур",
    unlocked: false,
  },
  {
    id: 2,
    icon: "⛵",
    titleRu: "Морская душа",
    descRu: "Побывал на морской прогулке на катере",
    unlocked: false,
  },
  {
    id: 3,
    icon: "🏝️",
    titleRu: "Исследователь островов",
    descRu: "Посетил остров Аскольд или Путятин",
    unlocked: false,
  },
  {
    id: 4,
    icon: "⛰️",
    titleRu: "Покоритель вершин",
    descRu: "Поднялся на сопку Сестра",
    unlocked: false,
  },
  {
    id: 5,
    icon: "🐅",
    titleRu: "Друг природы",
    descRu: "Побывал в Сафари Парке",
    unlocked: false,
  },
  {
    id: 6,
    icon: "🐬",
    titleRu: "Житель глубин",
    descRu: "Посетил Приморский океанариум",
    unlocked: false,
  },
  {
    id: 7,
    icon: "🏙️",
    titleRu: "Знаток Владивостока",
    descRu: "Прошёл пешеходную экскурсию по Владивостоку",
    unlocked: false,
  },
  {
    id: 8,
    icon: "🌸",
    titleRu: "Хранитель лотоса",
    descRu: "Увидел цветение лотосов на острове Путятин",
    unlocked: false,
  },
  {
    id: 9,
    icon: "💧",
    titleRu: "Охотник за водопадами",
    descRu: "Посетил водопад Стеклянуха",
    unlocked: false,
  },
  {
    id: 10,
    icon: "🌅",
    titleRu: "Ранняя пташка",
    descRu: "Забронировал тур за 7 и более дней до начала",
    unlocked: false,
  },
  {
    id: 11,
    icon: "🌟",
    titleRu: "Социальная звезда",
    descRu: "Привёл друга по реферальной ссылке",
    unlocked: false,
  },
  {
    id: 12,
    icon: "🏖️",
    titleRu: "Пляжный маньяк",
    descRu: "Посетил три разных пляжа и бухты",
    unlocked: false,
  },
  {
    id: 13,
    icon: "📸",
    titleRu: "Фотоохотник",
    descRu: "Побывал на пяти различных турах",
    unlocked: false,
  },
  {
    id: 14,
    icon: "🧭",
    titleRu: "Штурман",
    descRu: "Побывал и на морской, и на наземной экскурсии",
    unlocked: false,
  },
  {
    id: 15,
    icon: "🌿",
    titleRu: "Ботаник",
    descRu: "Посетил ботанический сад во Владивостоке",
    unlocked: false,
  },
  {
    id: 16,
    icon: "🔦",
    titleRu: "Маяк",
    descRu: "Увидел маяк Токаревский или Лихачёва",
    unlocked: false,
  },
  {
    id: 17,
    icon: "🏆",
    titleRu: "Преданный путешественник",
    descRu: "Совершил десять путешествий с Лотос-тур",
    unlocked: false,
  },
  {
    id: 18,
    icon: "💎",
    titleRu: "Жемчужина Ливадии",
    descRu: "Побывал в бухте Рифовая",
    unlocked: false,
  },
  {
    id: 19,
    icon: "🐆",
    titleRu: "След леопарда",
    descRu: "Побывал в национальном парке «Земля леопарда»",
    unlocked: false,
  },
  {
    id: 20,
    icon: "🌉",
    titleRu: "Стальная нить",
    descRu: "Пересёк Русский мост на остров Русский",
    unlocked: false,
  },
  {
    id: 21,
    icon: "🦀",
    titleRu: "Краболов",
    descRu: "Попробовал свежего камчатского краба в туре",
    unlocked: false,
  },
  {
    id: 22,
    icon: "⚓",
    titleRu: "Морской волк",
    descRu: "Прошёл три морских тура",
    unlocked: false,
  },
  {
    id: 23,
    icon: "🐋",
    titleRu: "Встреча с гигантом",
    descRu: "Увидел кита или косатку в заливе Петра Великого",
    unlocked: false,
  },
  {
    id: 24,
    icon: "🏰",
    titleRu: "Хранитель крепости",
    descRu: "Посетил форты Владивостокской крепости",
    unlocked: false,
  },
  {
    id: 25,
    icon: "❄️",
    titleRu: "Зимний странник",
    descRu: "Отправился в тур в зимний сезон",
    unlocked: false,
  },
  {
    id: 26,
    icon: "🎣",
    titleRu: "Удачный клёв",
    descRu: "Принял участие в рыболовном туре",
    unlocked: false,
  },
  {
    id: 27,
    icon: "🛶",
    titleRu: "Покоритель волн",
    descRu: "Прошёл маршрут на каяке или сапборде",
    unlocked: false,
  },
  {
    id: 28,
    icon: "🦇",
    titleRu: "Спелеолог",
    descRu: "Спустился в пещеры Екатериновского массива",
    unlocked: false,
  },
  {
    id: 29,
    icon: "⛺",
    titleRu: "Под звёздами",
    descRu: "Провёл ночь в палаточном лагере",
    unlocked: false,
  },
  {
    id: 30,
    icon: "🚂",
    titleRu: "Конечная станция",
    descRu: "Побывал на вокзале Владивостока — финише Транссиба",
    unlocked: false,
  },
  {
    id: 31,
    icon: "🦭",
    titleRu: "Друг нерпы",
    descRu: "Увидел нерп на лежбище во время сафари-тура",
    unlocked: false,
  },
];
